
object Twitter{
                       var twitterData = Seq(
                         (0,"12 actors who should play DJs along with James Van Der Beek"),
                         (0,"Miley Cyrus and the Flaming Lips are one big happy family on their new single"),
                         (0,"The first Friday of 2017 is off to a fantastic start thanks to new music from @EdSheeran"),
                         (0,"Watch Camila's final TV performances with Fifth Harmony"),
                         (0,"Loved @JamesArthur23 on @TODAYshow this AM! Check out #SayYouWontLetGo and some of his favorite songs."),
                         (0,"The 808 has become the fulcrum of hip hop - @Pharrell . #808themovie out now on @iTunes and @AppleMusic. #mustwatch #tr808 #hiphop"),
                         (0,"The most festive tracks from your favorite artists ❄️\nHoliday Pop Hits featuring @ArianaGrande, @maroon5, and more!"),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),
//                         (0,""),

                        (4, "The White House donates the Obama daughters' swing set"),
                        (4, "Donald Trump strongly condemned WikiLeaks in a 2010 interview, calling its actions spying and espionage"),
                        (4, "Many Hill Republicans are skeptical over Trump's plan to force Mexico's payment of a border wall"),
                         (4, "Trump's Electoral College win is certified despite Democratic objections"),
                        (4, "The 10 most damning findings from the report on Russian election interference"),
                        (4, "EXCLUSIVE: USSS Director Joseph Clancy says there is no friction with Donald Trump's private security teams"),
                        (4,"Trump orders all of Obama's political ambassadors to vacate their overseas posts by Inauguration Day"),
                        (4, "Donald Trump on the Russia hacking allegations: This is a political witch hunt"),
                        (4, "There's no friction at all with Trump's private security, the US Secret Service chief says"),
                        (4, "US intelligence identified the go-betweens Russians used to provide stolen emails to WikiLeaks, officials say"),
                        (4, "Democrats call for an ethics probe of Donald Trump's Health and Human Services nominee Rep. Tom Price "),
                        (4, "McCain: US intelligence agencies unanimously found Russia hacked US political organizations"),
                        (4, "Trump's transition team clashes with former Gen. James Mattis, the incoming secretary of defense, over Pentagon pick"),
                        (4, "11 times Vice President Biden was interrupted during Trump's electoral vote certification"),
                        (4, "Hillary Clinton will speak at a State Department event on Tuesday, January 10"),
                        (4, "With their agendas at odds, President Obama and President-elect Donald Trump's aides work to make nice"),
                        (4, "Sen. Tim Kaine: Why is Donald Trump acting like Russian President Vladimir Putin's defense lawye?"),
                        (4,"Trump's Electoral College win is certified despite Democratic objections "),
                         (4,"Obama in law journal: We cannot deny the legacy of racism that continues to drive inequality in the justice system "),
                         (4,"Obama asks his Cabinet to spell out its progress while offering incoming GOP officials its view of a path forward"),
                         (4,"Republican senators are setting up a possible confrontation with Trump in a hearing on Russian cyberhacks")
                      )

}