
object Twitter{
  //entertainment","health","money","sport","politics"
                       var twitterData = Seq(
                         (0,"12 actors who should play DJs along with James Van Der Beek"),
                         (0,"Miley Cyrus and the Flaming Lips are one big happy family on their new single"),
                         (0,"The first Friday of 2017 is off to a fantastic start thanks to new music from @EdSheeran"),
                         (0,"Watch Camila's final TV performances with Fifth Harmony"),
                         (0,"Loved @JamesArthur23 on @TODAYshow this AM! Check out #SayYouWontLetGo and some of his favorite songs."),
                         (0,"The 808 has become the fulcrum of hip hop - @Pharrell . #808themovie out now on @iTunes and @AppleMusic. #mustwatch #tr808 #hiphop"),
                         (0,"The most festive tracks from your favorite artists ❄Holiday Pop Hits featuring @ArianaGrande, @maroon5, and more!"),
                         (0,"Keep the festivities going with a playlist from the @TODAYshow!"),
                         (0,"From @chancetherapper to @RaeSremmurd to @6LACK, the #BestOfAppleMusic Hip-Hop has you covered."),
                         (0,"The Ohio trio @rascalflatts is back and their new single can literally be Yours If You Want It. Hit play!"),
                         (0,"The first #NMF of 2017 features new music from @Sia, @theflaminglips, @snakehipsuk & @MOMOMOYOUTH, and @TheShins"),
                         (0,"New Weird America #SoundsLike: indie folk/rock with a mix of metal, jazz, electronic, and even opera. Check it out"),
                         (0,"We teamed up with @Spotify to find music that will excite and inspire you on these amazing winter trips"),
                         (0,"Artists make the music, you listen to it, and #WeMemeIt."),
                         (0,"LEGO Batman's coming, and he's bringing some friends.Can you name them all? LEGO Batman Movie"),
                         (0,"Make plans to visit the Warner Bros. Studio Tour.  Click the link for more details!"),
                         (0,"Best Shows to Binge Watch on Netflix Right Now"),
                         (0,"Super Mario Maker Used to Recreate Game Boy's Super Mario Land"),
                         (0,"The seventh film in the Child's Play horror franchise, will include several characters from across the series."),
                         (0,"Here are nine potential directors that could replace @BenAffleck if he drops out of #TheBatman"),
                         (0,"Woody Harrelson is in talks to play Han Solo's mentor in next standalone Star Wars movie."),

                         (1,"Stay slim in 2017 with these 16 genius ways to lose weight fast"),
                         (1,"32 surprisingly simple ways to reverse all that holiday weight gain"),
                         (1,"Want to get rid of earwax? Here are the best and worst ways to clean your ears, according to a doctor"),
                         (1,"Keep those resolutions in tact with this fat-burning green smoothie"),
                         (1,"12 ways to fight stress and keep your heart healthy"),
                         (1,"Pneumonia is a catchall term for a range of lung infections. We break down which are serious vs easily treatable"),
                         (1,"How you can help your doctor speak your language with these simple steps"),
                         (1,"Not sure where to go when you're sick? We breakdown when you should see your PCP vs. when you should go to the ER."),
                         (1,"The FDA is encouraging the food industry to cut back on added salt, but will they?"),
                         (1,"Bronchiolitis: What parents of infants need to know about this potentially dangerous virus."),
                         (1,"The FDA warns that over-the-counter antacids w/aspirin can cause stomach bleeding in rare cases. "),
                         (1,"No surprise: Researchers found people stop exercising as they get older."),
                         (1,"Study says a CPAP machine may not slow heart disease down, but there are many other health benefits to using one."),
                         (1,"How to cope with a high blood pressure diagnosis when you live a healthy lifestyle"),
                         (1,"Study says millions of older adults aren't taking their blood pressure drugs as directed"),
                         (1,"Why understanding suicide in children & adolescents may lead to more effective prevention"),
                         (1,"The things that make doctors more efficient, make it harder for them to develop & maintain connections with patients"),
                         (1,"7 things you can do to avoid potentially dangerous drug interactions"),
                         (1,"Study says that it’s safe let babies feed themselves solid with parent supervision"),
                         (1,"New study says reading books may add years to your life"),
                         (1,"Use the three Rs —reminder, routine, and reward—to help you create good healthy habits"),

                           (2,"Forget the economy and corruption. Dirty air is China's most visible problem for many people"),
                           (2,"A time bomb is ticking in Europe's bond market"),
                           (2,"Americans start seeing enduring wage gains in a tighter job market"),
                           (2,"Libtard Juan Williams Claims the Recent Stock Market Growth is All From Obama"),
                           (2,"Historical day on the stock market! Thank you @realDonaldTrump mama is making massive dinero!!!! So happy!"),
                           (2,"Trump Is Right — Millions Of Illegals Probably Did Vote In 2016 | Stock News & Stock Market Analysis"),
                           (2,"Econ teacher is trying to teach me about the stock market like I haven't seen wolf of Wall Street 6 times"),
                           (2,"The stock market is projected to reach record numbers, I'm buying within oil. Thanks"),
                           (2,"kistan Stock Market up by 645.29 points, currently trading at 48,885. Making new records on daily basis! Yes This is Pakistan"),
                           (2,"Investors lost 6.2Lakh Cr in Modi regime. Even Pakistan stock market beats BSE/NSE for return on investment! Cluless Govt"),
                           (2,"Pakistan Stock Exchange ranked best in Asia and 5th best performing Stock Market in the World. "),
                           (2,"Short Interest in Tesla Motors, Inc. (TSLA) Declines By 0.8%: Tesla Motors, Inc. NASDAQ"),
                           (2,"Brokerages Set ADTRAN, Inc. (ADTN) Price Target at $22.00: Shares of ADTRAN, Inc. NASDAQ"),
                           (2,"The Marijuana Dealer Who Made It All The Way To The Nasdaq"),
                           (2,"Analyst Upgrades – Tesoro Logistics LP (NASDAQ:TLLP) Stock Gets Upgraded By Morgan Stanley from Equal Weight"),
                           (2,"Forget the economy and corruption. Dirty air is China's most visible problem for many people"),
                           (2,"Wall Street stock brokers don't need a business degree at all. They also work way less than me. Go ask them about their resume"),
                           (2,"The New Stock Market Where You Could Invest In The Empire State Building: Have you ever wanted business #news"),
                           (2,"Record stock market” shows UK has bright future says John Longworth, @LeaveMnsLeave co-chair and former BCC chief"),
                           (2,"Business Chief: Record Stock Market Shows Britain Has a Bright Future Outside EU"),
                           (2,"Why Adeboye Resigned For Obayemi to Lead RCCG - Business Post Nigeria Business News & Stock Market Reports "),

                           (3,"The #GameTime crew talk @memgrizz & preview their matchup w/ the @utahjazz Sunday night at 8pm ET on NBA TV."),
                           (3,"Go behind the scenes with @KristenLedlow as she tours England ahead of the NBA Global Games London 2017! #InsideStuff"),
                           (3,"Special #InsideStuff guest co-host @Andre discusses his career and the @Warriors’ season so far NBA"),
                           (3,"That defeat means QPR have equalled an unwanted record. They've now been eliminated at the #FACup 3rd Round 48 times - level with Plymouth."),
                           (3,"You can watch all the highlights and unique celebrationsfrom Saturday's FA Cup third round right here"),
                           (3,"Munster thrash Racing 92 in the Champions Cup tie rearranged after the death of their head coach Anthony Foley."),
                           (3,"8 players ejected after fight breaks out at UNLV vs. Utah State women’s basketball game"),
                           (3,"With a win over Texas Tech, #kubball became just the second team in NCAA Division I to have won 2,200 all-time games"),
                           (3,"Join USA Basketball in wishing 3-time Olympian, 3-time NBA Champion and 12-Time NBA All-Star @KingJames a very happy birthday"),
                           (3,"Last night @DaytonMBB logged its 3rd A-10 win beating R.I. by 3. @Archie_Miller says @__KP is looking like an all-conference player. #Dayton"),
                           (3,"Celebrate the USA Basketball Team of the Year & watch the video honoring US Olympic Men's & Women's Teams"),
                           (3,"Ready for a rematch? The last time these two played, the game was decided on a controversial no-call in Week 6. Seattle won 26-24."),
                           (3,"NBA teams have lost 662 consecutive games when trailing by at least 19 points entering 4th quarter. Grizzlies can snap that with a win"),
                           (3,"Mark Jackson just called out ESPN (his employer) for their obvious bias and disrespect for the Grizzlies. LISTEN and SHARE: "),
                           (3,"Knicks first win when trailing by at least 13 points entering the 4th quarter since Jan. 1, 2010 (trailed by 13 against Hawks)"),
                           (3,"Entering today, the Texans hadn't scored a first-quarter touchdown in 7 straight games. They have now. Houston 10, Oakland 0 on ESPN/ABC."),
                           (3,"Who'll be the @drpepper #OneFinalTeam raising the trophy after the Bama-Clemson rematch? Tell us who you're taking in Monday's title game!"),
                           (3,"We’re going into overtime in Oakland! Catch the Warriors vs. Grizzlies thriller on ESPN or here"),
                           (3,"Now available: Jose Fernandez: Passion for Baseball, Passion for Life by Clark Spencer"),
                           (3,"In today's MLB Roundup: How Tyson Ross could be the Cubs' next reclamation project."),
                           (3,"Kris Bryant turned 25 1/4. His 13.6 WAR in first two seasons is most by any position player. 2. Frank Robinson 13.4 3. Ted Williams 13.0."),

                        (4, "The White House donates the Obama daughters' swing set"),
                        (4, "Donald Trump strongly condemned WikiLeaks in a 2010 interview, calling its actions spying and espionage"),
                        (4, "Many Hill Republicans are skeptical over Trump's plan to force Mexico's payment of a border wall"),
                         (4, "Trump's Electoral College win is certified despite Democratic objections"),
                        (4, "The 10 most damning findings from the report on Russian election interference"),
                        (4, "EXCLUSIVE: USSS Director Joseph Clancy says there is no friction with Donald Trump's private security teams"),
                        (4,"Trump orders all of Obama's political ambassadors to vacate their overseas posts by Inauguration Day"),
                        (4, "Donald Trump on the Russia hacking allegations: This is a political witch hunt"),
                        (4, "There's no friction at all with Trump's private security, the US Secret Service chief says"),
                        (4, "US intelligence identified the go-betweens Russians used to provide stolen emails to WikiLeaks, officials say"),
                        (4, "Democrats call for an ethics probe of Donald Trump's Health and Human Services nominee Rep. Tom Price "),
                        (4, "McCain: US intelligence agencies unanimously found Russia hacked US political organizations"),
                        (4, "Trump's transition team clashes with former Gen. James Mattis, the incoming secretary of defense, over Pentagon pick"),
                        (4, "11 times Vice President Biden was interrupted during Trump's electoral vote certification"),
                        (4, "Hillary Clinton will speak at a State Department event on Tuesday, January 10"),
                        (4, "With their agendas at odds, President Obama and President-elect Donald Trump's aides work to make nice"),
                        (4, "Sen. Tim Kaine: Why is Donald Trump acting like Russian President Vladimir Putin's defense lawye?"),
                        (4,"Trump's Electoral College win is certified despite Democratic objections "),
                         (4,"Obama in law journal: We cannot deny the legacy of racism that continues to drive inequality in the justice system "),
                         (4,"Obama asks his Cabinet to spell out its progress while offering incoming GOP officials its view of a path forward"),
                         (4,"Republican senators are setting up a possible confrontation with Trump in a hearing on Russian cyberhacks")
                      )

}